const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000/api';
const API_VERSION = import.meta.env.VITE_API_VERSION || 'v1';

export const URLS = {
    API_URL: API_BASE_URL+ '/' + API_VERSION,
    APP_CONFIG: '/app-configs',
    ADMIN_CONFIGURE: '/admin/configure',
    CHECK_PERMISSIONS: '/check-permissions',
    SEARCH : '/search',
    GET_ENTRY: '/get-entry',
    CHECK_ENTRY_ACCESS: '/check-entry-access',
    CHECK_ENTRY_WRITE_ACCESS: '/check-entry-write-access',
    UPDATE_ENTRY: '/update-entry',
    GET_ENTRY_BY_FQN: '/get-entry-by-fqn',
    LOOKUP_ENTRY_LINKS: '/lookup-entry-links',
    GET_SAMPLE_DATA: '/get-sample-data',
    BATCH_ASPECTS: '/batch-aspects',
    LINEAGE_SEARCH: '/lineage',
    ENTRY_DATA_QUALITY: '/entry-data-quality',
    GET_DATA_SCAN: '/get-data-scan',
    GET_ALL_DATA_SCANS: '/data-scans',
    GET_ASPECT_DETAIL: '/get-aspect-detail',
    GET_PROCESS_AND_JOB_DETAILS : '/get-process-and-job-details',
    ACCESS_REQUEST : '/access-request',
    GET_PROJECTS: '/get-projects',
    SEND_FEEDBACK: '/send-feedback',
    LINEAGE_SEARCH_COLUMN_LEVEL: '/lineage-column-level',
    GET_SCAN_JOBS: '/get-data-scan-jobs',
    DATA_PRODUCTS: '/data-products',
    DATA_PRODUCT_DETAILS: '/data-product-details',
    DATA_PRODUCT_ASSETS: '/data-product-assets',
    GLOSSARY_CHILDREN: '/glossary-children',
    LOOKUP_ENTRY_REST: '/lookup-entry-rest',
    SEARCH_ENTRIES: '/search-entries',
}